import { describe, expect, it, vi } from 'vitest';
import type { Feature, Polygon } from 'geojson';
import type { Stop } from '../../types/gtfs';
import {
  regionForState,
  isInUS,
  bboxFromStops,
  unionWalkshedPolygons,
  tabulateBlocks,
  loadBlocksInBbox,
  CoverageLayerSchemaError,
  type BlockPoint,
} from '../blockCoverage';

/** Drive loadBlocksInBbox against a stubbed FlatGeobuf stream. */
const fgbFeatures = vi.hoisted(() => ({ current: [] as unknown[] }));
vi.mock('flatgeobuf', () => ({
  geojson: {
    deserialize: () => (async function* () {
      for (const f of fgbFeatures.current) yield f;
    })(),
  },
}));

function fgbPoint(props: Record<string, unknown>) {
  return {
    type: 'Feature',
    geometry: { type: 'Point', coordinates: [-111, 46] },
    properties: props,
  };
}

/** A synthetic census block point. Defaults to all-zero attributes; override
 *  the ones a test cares about. */
function blk(geoid: string, lon: number, lat: number, attrs: Partial<BlockPoint> = {}): BlockPoint {
  return {
    geoid, lon, lat,
    pop: 0, hh: 0, workers: 0,
    minority: 0, race_pop: 0, lowinc: 0, pov_univ: 0,
    zeroveh_hh: 0, occ_hh: 0, senior: 0, youth: 0,
    carless: 0, disability: 0, prop_all: 0, need_all: 0, jobs: 0,
    ...attrs,
  };
}

/** Axis-aligned square polygon centred on (lon, lat) with half-width `half` deg. */
function square(lon: number, lat: number, half: number): Feature<Polygon> {
  return {
    type: 'Feature',
    properties: {},
    geometry: {
      type: 'Polygon',
      coordinates: [[
        [lon - half, lat - half],
        [lon + half, lat - half],
        [lon + half, lat + half],
        [lon - half, lat + half],
        [lon - half, lat - half],
      ]],
    },
  };
}

function stop(id: string, lon: number, lat: number): Stop {
  return { stop_id: id, stop_name: id, stop_lat: lat, stop_lon: lon, location_type: 0, wheelchair_boarding: 0 };
}

describe('regionForState / isInUS', () => {
  it('maps the 50 states + DC to the us block region, territories/unknown to null', () => {
    expect(regionForState('30')).toBe('us'); // Montana
    expect(regionForState('06')).toBe('us'); // California
    expect(regionForState('11')).toBe('us'); // DC
    expect(regionForState('72')).toBeNull(); // Puerto Rico (territory, not in us.fgb)
    expect(regionForState('99')).toBeNull(); // unknown
  });

  it('bounds-checks US coordinates (CONUS + AK + HI)', () => {
    expect(isInUS(46.6, -111.9)).toBe(true); // Helena, MT
    expect(isInUS(37.8, -122.2)).toBe(true); // Oakland, CA
    expect(isInUS(61.2, -149.9)).toBe(true); // Anchorage, AK
    expect(isInUS(21.3, -157.8)).toBe(true); // Honolulu, HI
    expect(isInUS(51.5, -0.13)).toBe(false); // London
  });
});

describe('loadBlocksInBbox — stale-layer guard', () => {
  const bbox = { minX: -112, minY: 45, maxX: -110, maxY: 47 };

  it('rejects a layer on the OLD schema instead of reading its unions as zero', async () => {
    // The live us.fgb is a 1.6 GB artifact regenerated by a separate, deliberate
    // run, so the client and the layer ship independently. Point this code at an
    // old layer and `prop_all` is simply absent: `Number(undefined) || 0` would
    // make it 0, and the panel would print "Ridership propensity: 0" — a
    // confident, specific, wrong number that looks exactly like a real one.
    //
    // A missing estimate must never render as a zero estimate. A stale layer is
    // treated as NO layer; the caller falls back to counts and says so.
    fgbFeatures.current = [
      fgbPoint({
        geoid: 'A', pop: 100, hh: 40, workers: 50, minority: 20, race_pop: 100,
        lowinc: 30, pov_univ: 90, zeroveh_hh: 5, occ_hh: 40, senior: 12, youth: 18,
        riders: 45, // the RETIRED column — this is what an old layer looks like
        jobs: 10,
      }),
    ];
    await expect(loadBlocksInBbox('us', bbox)).rejects.toBeInstanceOf(CoverageLayerSchemaError);
    await expect(loadBlocksInBbox('us', bbox)).rejects.toThrow(/older schema/);
    await expect(loadBlocksInBbox('us', bbox)).rejects.toThrow(/prop_all/);
  });

  it('accepts a layer carrying the union columns and parses them', async () => {
    fgbFeatures.current = [
      fgbPoint({
        geoid: 'A', pop: 100, hh: 40, workers: 50, minority: 20, race_pop: 100,
        lowinc: 30, pov_univ: 90, zeroveh_hh: 5, occ_hh: 40, senior: 12, youth: 18,
        carless: 10, disability: 8, prop_all: 35, need_all: 50, jobs: 10,
      }),
    ];
    const blocks = await loadBlocksInBbox('us', bbox);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].prop_all).toBe(35);
    expect(blocks[0].need_all).toBe(50);
    expect(blocks[0].carless).toBe(10);
    expect(blocks[0].disability).toBe(8);
  });
});

describe('bboxFromStops', () => {
  it('returns a padded bbox covering all stops', () => {
    const bbox = bboxFromStops([stop('a', -112, 46), stop('b', -111, 47)], 0.02);
    expect(bbox).not.toBeNull();
    expect(bbox!.minX).toBeCloseTo(-112.02, 6);
    expect(bbox!.maxX).toBeCloseTo(-110.98, 6);
    expect(bbox!.minY).toBeCloseTo(45.98, 6);
    expect(bbox!.maxY).toBeCloseTo(47.02, 6);
  });

  it('returns null for an empty stop set', () => {
    expect(bboxFromStops([])).toBeNull();
  });
});

describe('tabulateBlocks', () => {
  // A 0.1°-half-width square centred on (-111, 46): contains the two "inside"
  // blocks, excludes the far one.
  const walkshed = square(-111, 46, 0.1);

  const blocks = [
    blk('A', -111.0, 46.0, {
      pop: 100, hh: 40, workers: 50, minority: 20, race_pop: 100, lowinc: 30,
      senior: 12, disability: 8, carless: 10, prop_all: 35, need_all: 50, jobs: 10,
    }),
    blk('B', -110.95, 46.05, {
      pop: 50, hh: 20, workers: 25, minority: 5, race_pop: 50, lowinc: 15,
      senior: 6, disability: 4, carless: 5, prop_all: 18, need_all: 25, jobs: 200,
    }),
    blk('C', -110.0, 46.0, {
      pop: 9999, hh: 9999, workers: 9999, minority: 9999, race_pop: 9999, lowinc: 9999,
      senior: 9999, disability: 9999, carless: 9999, prop_all: 9999, need_all: 9999, jobs: 9999,
    }),
  ];

  it('sums attributes only for blocks whose centroid is inside the walkshed', () => {
    const r = tabulateBlocks(blocks, walkshed);
    expect(r.blocksCovered).toBe(2);
    expect(r.blocksTotal).toBe(3);
    expect(r.coveredBlockGroupIds.sort()).toEqual(['A', 'B']);
    expect(r.totalPopulation).toBe(150);
    expect(r.totalHouseholds).toBe(60);
    expect(r.totalWorkers).toBe(75);
    expect(r.minorityPop).toBe(25);
    expect(r.totalRacePop).toBe(150);
    expect(r.totalJobs).toBe(210); // includes B's job-heavy block
    // The new schema: the two ACS segments the layer gained, and the two unions.
    expect(r.carlessPop).toBe(15);
    expect(r.disabilityPop).toBe(12);
    expect(r.propensityAll).toBe(53);
    expect(r.needAll).toBe(75);
  });

  it('sums the unions across blocks (blocks are disjoint, so no dedup is owed here)', () => {
    // Deduplication happens WITHIN a geography, offline, from PUMS. Two different
    // census blocks never share a person, so the walkshed's union is simply the
    // sum of the per-block unions — and it must still contain each segment.
    const r = tabulateBlocks(blocks, walkshed);
    expect(r.propensityAll).toBe(35 + 18);
    expect(r.needAll).toBe(50 + 25);
    expect(r.carlessPop).toBeLessThanOrEqual(r.propensityAll);
    expect(r.lowIncomePop).toBeLessThanOrEqual(r.propensityAll);
    expect(r.propensityAll).toBeLessThanOrEqual(r.needAll);
    expect(r.seniorPop).toBeLessThanOrEqual(r.needAll);
    expect(r.disabilityPop).toBeLessThanOrEqual(r.needAll);
    expect(r.needAll).toBeLessThanOrEqual(r.totalPopulation);
  });

  it('reports the propensity union as DE-DUPLICATED, below the sum of its two segments', () => {
    // The property the retired ×0.6 model failed: |A ∪ B| < |A| + |B| whenever the
    // groups overlap, and |A ∪ B| ≥ max(|A|, |B|) always.
    const r = tabulateBlocks(blocks, walkshed);
    expect(r.propensityAll).toBeLessThan(r.carlessPop + r.lowIncomePop);
    expect(r.propensityAll).toBeGreaterThanOrEqual(Math.max(r.carlessPop, r.lowIncomePop));
  });

  it('counts a block once under union semantics across overlapping walksheds', () => {
    // Two overlapping squares; block A sits in the overlap, B in only one.
    const s1 = square(-111.0, 46.0, 0.08);
    const s2 = square(-110.95, 46.05, 0.08);
    const unioned = unionWalkshedPolygons([s1, s2]);
    expect(unioned).not.toBeNull();
    const r = tabulateBlocks(blocks, unioned);
    expect(r.blocksCovered).toBe(2); // A counted once despite being in both
    expect(r.totalPopulation).toBe(150);
    expect(r.totalJobs).toBe(210);
  });

  it('falls back to per-feature OR testing when no union polygon is available', () => {
    const s1 = square(-111.0, 46.0, 0.03); // contains A only
    const s2 = square(-110.95, 46.05, 0.03); // contains B only
    const r = tabulateBlocks(blocks, null, [s1, s2]);
    expect(r.blocksCovered).toBe(2);
    expect(r.totalPopulation).toBe(150);
  });

  it('returns zeroed totals when nothing is inside', () => {
    const empty = square(0, 0, 0.01);
    const r = tabulateBlocks(blocks, empty);
    expect(r.blocksCovered).toBe(0);
    expect(r.totalPopulation).toBe(0);
    expect(r.totalJobs).toBe(0);
  });
});
