// Detector is intentionally conservative (see the TODO in rtapDetect.ts) —
// these tests pin down "no signal → isRtap:false" as much as the positive
// matches, since silence is the overwhelmingly common case. A prior content-
// based structural fingerprint was measured against 251 real RTAP feeds and
// removed (3% sensitivity, one signal anti-correlated) — see the TODO for the
// numbers. Detection is now keyed on the source URL (provenance) plus the
// pre-existing free-text string checks.
import { describe, expect, it } from 'vitest';
import { detectRtapFeed } from '../rtapDetect';
import type { FeedInfo, Agency } from '../../types/gtfs';

const AGENCY = (overrides: Partial<Agency> = {}): Agency => ({
  agency_id: 'a1',
  agency_name: 'Anytown Transit',
  agency_url: 'https://anytowntransit.example.org',
  agency_timezone: 'America/Denver',
  ...overrides,
});

const FEED_INFO = (overrides: Partial<FeedInfo> = {}): FeedInfo => ({
  feed_publisher_name: 'Anytown Transit',
  feed_publisher_url: 'https://anytowntransit.example.org',
  feed_lang: 'en-US',
  ...overrides,
});

describe('detectRtapFeed', () => {
  it('defaults to isRtap:false with no signals when nothing is RTAP-branded', () => {
    const result = detectRtapFeed(FEED_INFO(), [AGENCY()]);
    expect(result).toEqual({ isRtap: false, confidence: 'low', signals: [] });
  });

  it('handles null/undefined feed_info and empty agencies without throwing', () => {
    expect(detectRtapFeed(null, [])).toEqual({ isRtap: false, confidence: 'low', signals: [] });
    expect(detectRtapFeed(undefined, [])).toEqual({ isRtap: false, confidence: 'low', signals: [] });
  });

  it('flags high confidence on an exact "National RTAP" mention in feed_publisher_name', () => {
    const result = detectRtapFeed(FEED_INFO({ feed_publisher_name: 'National RTAP' }), []);
    expect(result.isRtap).toBe(true);
    expect(result.confidence).toBe('high');
    expect(result.signals.length).toBeGreaterThan(0);
  });

  it('flags high confidence on a nationalrtap.org URL in feed_publisher_url', () => {
    const result = detectRtapFeed(FEED_INFO({ feed_publisher_url: 'https://www.nationalrtap.org/gtfs' }), []);
    expect(result.isRtap).toBe(true);
    expect(result.confidence).toBe('high');
  });

  it('flags high confidence when the signal is on agency.txt rather than feed_info.txt', () => {
    const result = detectRtapFeed(null, [AGENCY({ agency_url: 'https://nationalrtap.org' })]);
    expect(result.isRtap).toBe(true);
    expect(result.confidence).toBe('high');
  });

  it('flags low confidence on a bare "RTAP" mention without the full org name/domain', () => {
    const result = detectRtapFeed(FEED_INFO({ feed_version: 'built with RTAP tools' }), []);
    expect(result.isRtap).toBe(true);
    expect(result.confidence).toBe('low');
  });

  it('flags low confidence on a "GTFS Builder" mention', () => {
    const result = detectRtapFeed(FEED_INFO({ feed_publisher_name: 'Generated by GTFS Builder' }), []);
    expect(result.isRtap).toBe(true);
    expect(result.confidence).toBe('low');
  });

  it('does not false-positive on unrelated substrings', () => {
    // "rtap" must be a whole word — shouldn't match inside an unrelated token.
    const result = detectRtapFeed(FEED_INFO({ feed_publisher_name: 'Startapp Transit Co' }), []);
    expect(result.isRtap).toBe(false);
  });

  // ── sourceUrl provenance — the primary signal now that the content
  // fingerprint has been retired (measured at 3% sensitivity; see the TODO) ──
  describe('sourceUrl provenance', () => {
    it('flags high confidence for a rapid.nationalrtap.org source URL', () => {
      const result = detectRtapFeed(
        FEED_INFO(),
        [AGENCY()],
        'http://rapid.nationalrtap.org/GTFSFileManagement/UserUploadFiles/11497/Skyline_GTFS.zip',
      );
      expect(result.isRtap).toBe(true);
      expect(result.confidence).toBe('high');
    });

    it('flags high confidence for a demopro.nationalrtap.org source URL (older feeds)', () => {
      const result = detectRtapFeed(FEED_INFO(), [AGENCY()], 'https://demopro.nationalrtap.org/some/feed.zip');
      expect(result.isRtap).toBe(true);
      expect(result.confidence).toBe('high');
    });

    it('flags high confidence for the bare apex domain', () => {
      const result = detectRtapFeed(FEED_INFO(), [AGENCY()], 'https://nationalrtap.org/feed.zip');
      expect(result.isRtap).toBe(true);
      expect(result.confidence).toBe('high');
    });

    it('does NOT match a lookalike host that merely contains the domain as a substring', () => {
      // Proves the host is parsed via URL(), not string-matched — a suffix
      // like ".evil.com" after "nationalrtap.org" must not count.
      const result = detectRtapFeed(FEED_INFO(), [AGENCY()], 'https://nationalrtap.org.evil.com/feed.zip');
      expect(result.isRtap).toBe(false);
    });

    it('does NOT match a lookalike host that merely shares a suffix', () => {
      // "notnationalrtap.org" is NOT a subdomain of nationalrtap.org.
      const result = detectRtapFeed(FEED_INFO(), [AGENCY()], 'https://notnationalrtap.org/feed.zip');
      expect(result.isRtap).toBe(false);
    });

    it('does not fire on an arbitrary, unrelated agency/hosting URL', () => {
      const result = detectRtapFeed(FEED_INFO(), [AGENCY()], 'https://files.mobilitydatabase.org/some-feed.zip');
      expect(result.isRtap).toBe(false);
    });

    it('does not throw and does not fire on a malformed/relative sourceUrl', () => {
      expect(() => detectRtapFeed(FEED_INFO(), [AGENCY()], 'not-a-url')).not.toThrow();
      expect(detectRtapFeed(FEED_INFO(), [AGENCY()], 'not-a-url').isRtap).toBe(false);
    });

    it('does not fire when sourceUrl is undefined/null and the feed carries no RTAP string', () => {
      // This is the real Skyline Bus / Big Sky MT sample: an actual National
      // RTAP GTFS Builder export that mentions "rtap" NOWHERE in its data. For
      // a bare ZIP upload (no known source URL) this is the honest, correct
      // answer — we cannot tell RTAP provenance from bytes alone.
      const skylineFeedInfo = FEED_INFO({
        feed_publisher_name: 'Skyline Bus',
        feed_publisher_url: 'https://skylinebus.com/',
      });
      const skylineAgency = [AGENCY({ agency_name: 'Skyline Bus', agency_url: 'https://skylinebus.com/' })];
      expect(detectRtapFeed(skylineFeedInfo, skylineAgency, undefined)).toEqual({
        isRtap: false, confidence: 'low', signals: [],
      });
      expect(detectRtapFeed(skylineFeedInfo, skylineAgency, null)).toEqual({
        isRtap: false, confidence: 'low', signals: [],
      });
    });
  });
});
