// Feature gating — which plans unlock which capabilities.
// See docs/REQUIREMENTS.md for the source-of-truth tier/feature map.
// NOTE: this matrix is mirrored by hand in src/components/billing/planConfig.ts —
// edit BOTH in lockstep.

import type { Plan } from '../projects/quotas';

export type FeatureKey =
  | 'managed_publishing'   // POST /api/projects/:id/publish → canonical URL + embeds
  | 'draft_links'          // POST /api/projects/:id/draft-links → public share URLs
  | 'mobility_db_submit'   // submit feed to Mobility Database
  | 'embeds'               // rider-facing embed widgets + mini-site
  | 'embed_remove_badge'   // serve embeds without the "Powered by GTFS·X" badge
  | 'snapshot_history'     // named snapshots + restore + delete
  | 'analysis_basic'       // demographic coverage + cost estimation
  | 'analysis_title_vi'    // Title VI equity analysis
  | 'analysis_propensity'  // propensity heatmap
  | 'network_walksheds'    // street-network (Mapbox isochrone) coverage walksheds
  | 'org_workspace'        // create or be a member of an org
  | 'cross_org_member'     // member of orgs you don't own (e.g. consultants in client orgs)
  | 'org_logo'             // upload a custom org logo
  | 'brand_color'          // custom brand primary color
  | 'service_alerts'       // author GTFS-Realtime Service Alerts
  | 'scenarios'            // save + switch named route-visibility sets
  | 'phone_support';       // SLA-backed phone support

// Per-feature: which plans grant access. Free is excluded by absence.
//
// Pricing v3 (Jun 2026): richer, more shareable free tier without giving away
// the two paid pillars (hosting/embeds + route-level analysis). Demand dots
// (analysis_propensity) are free for everyone; the cost & coverage panels split
// into a free system-level summary and a paywalled route-level breakdown
// (analysis_basic stays Agency+). Embeds stay Pro+, but only Agency+ may remove
// the "Powered by GTFS·X" badge (embed_remove_badge). phone_support moves to
// Agency+ to match the catalog.
export const FEATURE_PLANS: Record<FeatureKey, readonly Plan[]> = {
  managed_publishing:  ['pro', 'agency', 'enterprise'],
  draft_links:         ['pro', 'agency', 'enterprise'],
  mobility_db_submit:  ['pro', 'agency', 'enterprise'],
  embeds:              ['pro', 'agency', 'enterprise'],
  embed_remove_badge:  ['agency', 'enterprise'],
  snapshot_history:    ['pro', 'agency', 'enterprise'],
  analysis_basic:      ['agency', 'enterprise'],
  analysis_title_vi:   ['agency', 'enterprise'],
  analysis_propensity: ['free', 'pro', 'agency', 'enterprise'],
  network_walksheds:   ['agency', 'enterprise'],
  org_workspace:       ['agency', 'enterprise'],
  cross_org_member:    ['agency', 'enterprise'],
  org_logo:            ['agency', 'enterprise'],
  brand_color:         ['pro', 'agency', 'enterprise'],
  service_alerts:      ['agency', 'enterprise'],
  scenarios:           ['agency', 'enterprise'],
  phone_support:       ['agency', 'enterprise'],
};

export function planHasFeature(plan: Plan, feature: FeatureKey): boolean {
  return FEATURE_PLANS[feature].includes(plan);
}

// The smallest plan that unlocks a given feature — used by the upgrade modal
// to suggest a target. Order matches the price ladder.
const PLAN_ORDER: Plan[] = ['free', 'pro', 'agency', 'enterprise'];

export function cheapestPlanFor(feature: FeatureKey): Plan {
  for (const plan of PLAN_ORDER) {
    if (planHasFeature(plan, feature)) return plan;
  }
  return 'enterprise';
}

// Whether a plan represents a billable subscription (vs. free / staff-granted enterprise).
export function isPaidPlan(plan: Plan): boolean {
  return plan !== 'free';
}

// Public copy used by the pricing page and paywall overlays. Kept in sync with
// the Stripe Product metadata generated by scripts/setup-stripe.ts.
export interface PlanCatalogEntry {
  plan: Plan;
  displayName: string;
  monthlyPriceUsd: number | null;   // null = invoice-only (enterprise)
  annualPriceUsd: number | null;
  perSeat: boolean;
  tagline: string;
  features: string[];
  // Optional "see more" link rendered below the bullet list (e.g. the Agency
  // card → the /planning reference page).
  detailsHref?: string;
  detailsLabel?: string;
}

export const PLAN_CATALOG: PlanCatalogEntry[] = [
  {
    plan: 'free',
    displayName: 'Free',
    monthlyPriceUsd: 0,
    annualPriceUsd: 0,
    perSeat: false,
    tagline: 'Create, edit, validate, and export GTFS feeds — in your browser.',
    features: [
      'Create and edit routes, stops, trips, and schedules on a live map',
      'Add GTFS-Flex zones and booking rules to any feed',
      'Validate against the GTFS spec as you work',
      'Import an existing feed or start from scratch — no signup required',
      'Export a spec-clean GTFS .zip and host it anywhere',
      'Up to 3 saved feeds in the cloud',
      'Nationwide demand-propensity map',
      'Community support',
    ],
  },
  {
    plan: 'pro',
    displayName: 'Pro',
    monthlyPriceUsd: 49,
    annualPriceUsd: 499,
    perSeat: false,
    tagline: 'Host and publish feeds.',
    features: [
      'Up to 10 saved feeds',
      'Publish 1 feed to a stable URL',
      'Rider-facing embeds + mini-site (with GTFS·X badge)',
      'Submit to the Mobility Database',
      'Named snapshot history',
      'Custom brand color',
      'Email support',
    ],
  },
  {
    plan: 'agency',
    displayName: 'Agency',
    monthlyPriceUsd: 299,
    annualPriceUsd: 2499,
    perSeat: false,
    tagline: 'Plan routes and service as a team.',
    features: [
      'Everything in Pro',
      'Unlimited feeds',
      'Route operating cost estimates',
      'Demographic coverage analysis',
      'Title VI equity analysis',
      'Scenario comparison',
      'Service Alerts authoring (GTFS-Realtime)',
      'Fully white-labeled rider site (your domain, your brand)',
      'Unlimited team members',
      'Cross-org membership for consultants',
      'Custom org logo',
      'Phone + email support',
    ],
    detailsHref: '/planning',
    detailsLabel: 'See all planning features →',
  },
  {
    plan: 'enterprise',
    displayName: 'Enterprise',
    monthlyPriceUsd: null,
    annualPriceUsd: null,
    perSeat: false,
    tagline: 'For state DOTs, RTAP networks, and large consortiums.',
    features: [
      'Custom feed and seat limits',
      'Unlimited Premium Feed Management',
      'Branded mini-sites',
      'Full Route Planning Features',
      'Phone + email support with SLA',
      'Contract terms via PO or invoice',
    ],
  },
];
