// Feature gating — which plans unlock which capabilities.
// See docs/FREEMIUM_PLAN.md §1.1 for the source-of-truth matrix.

import type { Plan } from '../projects/quotas';

export type FeatureKey =
  | 'managed_publishing'   // POST /api/projects/:id/publish → canonical URL + embeds
  | 'draft_links'          // POST /api/projects/:id/draft-links → public share URLs
  | 'mobility_db_submit'   // submit feed to Mobility Database
  | 'embeds'               // rider-facing embed widgets + mini-site
  | 'snapshot_history'     // named snapshots + restore + delete
  | 'analysis_basic'       // demographic coverage + cost estimation
  | 'analysis_title_vi'    // Title VI equity analysis
  | 'analysis_propensity'  // propensity heatmap
  | 'org_workspace'        // create or be a member of an org
  | 'cross_org_member'     // member of orgs you don't own (e.g. consultants in client orgs)
  | 'org_logo'             // upload a custom org logo
  | 'brand_color'          // custom brand primary color
  | 'service_alerts'       // author GTFS-Realtime Service Alerts
  | 'phone_support';       // SLA-backed phone support

// Per-feature: which plans grant access. Free is excluded by absence.
//
// Pricing v2 (May 2026): Pro is positioned as the "host and publish feeds"
// tier — all publishing-adjacent features live here. The Agency tier (DB id:
// 'agency') consolidates the planning/analysis suite so it competes head-to-head
// with Remix at ~1/6 of Remix's price. The single feature that moved was
// analysis_basic (cost + coverage), reassigned from Pro to Agency-and-up.
export const FEATURE_PLANS: Record<FeatureKey, readonly Plan[]> = {
  managed_publishing:  ['pro', 'agency', 'enterprise'],
  draft_links:         ['pro', 'agency', 'enterprise'],
  mobility_db_submit:  ['pro', 'agency', 'enterprise'],
  embeds:              ['pro', 'agency', 'enterprise'],
  snapshot_history:    ['pro', 'agency', 'enterprise'],
  analysis_basic:      ['agency', 'enterprise'],
  analysis_title_vi:   ['agency', 'enterprise'],
  analysis_propensity: ['agency', 'enterprise'],
  org_workspace:       ['agency', 'enterprise'],
  cross_org_member:    ['agency', 'enterprise'],
  org_logo:            ['agency', 'enterprise'],
  brand_color:         ['pro', 'agency', 'enterprise'],
  service_alerts:      ['agency', 'enterprise'],
  phone_support:       ['enterprise'],
};

export function planHasFeature(plan: Plan, feature: FeatureKey): boolean {
  return FEATURE_PLANS[feature].includes(plan);
}

// The smallest plan that unlocks a given feature — used by the upgrade modal
// to suggest a target. Order matches the price ladder.
const PLAN_ORDER: Plan[] = ['free', 'pro', 'agency', 'enterprise'];

export function cheapestPlanFor(feature: FeatureKey): Plan {
  for (const plan of PLAN_ORDER) {
    if (planHasFeature(plan, feature)) return plan;
  }
  return 'enterprise';
}

// Whether a plan represents a billable subscription (vs. free / staff-granted enterprise).
export function isPaidPlan(plan: Plan): boolean {
  return plan !== 'free';
}

// Public copy used by the pricing page and paywall overlays. Kept in sync with
// the Stripe Product metadata generated by scripts/setup-stripe.ts.
export interface PlanCatalogEntry {
  plan: Plan;
  displayName: string;
  monthlyPriceUsd: number | null;   // null = invoice-only (enterprise)
  annualPriceUsd: number | null;
  perSeat: boolean;
  tagline: string;
  features: string[];
}

export const PLAN_CATALOG: PlanCatalogEntry[] = [
  {
    plan: 'free',
    displayName: 'Free',
    monthlyPriceUsd: 0,
    annualPriceUsd: 0,
    perSeat: false,
    tagline: 'Edit and export feeds.',
    features: [
      'Up to 3 saved feeds in the cloud',
      'GTFS ZIP export (host anywhere)',
      'Free forever',
      'Community support',
    ],
  },
  {
    plan: 'pro',
    displayName: 'Pro',
    monthlyPriceUsd: 49,
    annualPriceUsd: 499,
    perSeat: false,
    tagline: 'Host and publish feeds.',
    features: [
      'Up to 10 saved feeds',
      'Publish 1 feed to a stable URL',
      'Rider-facing embeds + mini-site',
      'Submit to the Mobility Database',
      'Named snapshot history',
      'Custom brand color',
      'Email support',
    ],
  },
  {
    plan: 'agency',
    displayName: 'Agency',
    monthlyPriceUsd: 299,
    annualPriceUsd: 2499,
    perSeat: false,
    tagline: 'Plan routes and service as a team.',
    features: [
      'Everything in Pro',
      'Unlimited feeds',
      'Demographic coverage analysis',
      'Cost estimation analysis',
      'Title VI equity analysis',
      'Ridership propensity heatmap',
      'Service Alerts authoring (GTFS-Realtime)',
      'Unlimited team members in your organization',
      'Cross-org membership (work in unlimited client orgs)',
      'Custom org logo',
      'Phone support',
    ],
  },
  {
    plan: 'enterprise',
    displayName: 'Enterprise',
    monthlyPriceUsd: null,
    annualPriceUsd: null,
    perSeat: false,
    tagline: 'For state DOTs, RTAP networks, and large consortiums.',
    features: [
      'Custom feed and seat limits',
      'Unlimited Premium Feed Management',
      'Branded mini-sites',
      'Full Route Planning Features',
      'Phone + email support with SLA',
      'Contract terms via PO or invoice',
    ],
  },
];
