// Feature gating — which plans unlock which capabilities.
// See docs/FREEMIUM_PLAN.md §1.1 for the source-of-truth matrix.

import type { Plan } from '../projects/quotas';

export type FeatureKey =
  | 'managed_publishing'   // POST /api/projects/:id/publish → canonical URL + embeds
  | 'draft_links'          // POST /api/projects/:id/draft-links → public share URLs
  | 'mobility_db_submit'   // submit feed to Mobility Database
  | 'embeds'               // rider-facing embed widgets + mini-site
  | 'analysis_basic'       // demographic coverage + cost estimation
  | 'analysis_title_vi'    // Title VI equity analysis
  | 'analysis_propensity'  // propensity heatmap
  | 'org_workspace'        // create or be a member of an org
  | 'cross_org_member'     // member of orgs you don't own (e.g. consultants in client orgs)
  | 'org_logo'             // upload a custom org logo
  | 'brand_color'          // custom brand primary color
  | 'phone_support';       // SLA-backed phone support

// Per-feature: which plans grant access. Free is excluded by absence.
export const FEATURE_PLANS: Record<FeatureKey, readonly Plan[]> = {
  managed_publishing:  ['pro', 'team', 'enterprise'],
  draft_links:         ['pro', 'team', 'enterprise'],
  mobility_db_submit:  ['pro', 'team', 'enterprise'],
  embeds:              ['pro', 'team', 'enterprise'],
  analysis_basic:      ['pro', 'team', 'enterprise'],
  analysis_title_vi:   ['team', 'enterprise'],
  analysis_propensity: ['team', 'enterprise'],
  org_workspace:       ['team', 'enterprise'],
  cross_org_member:    ['team', 'enterprise'],
  org_logo:            ['team', 'enterprise'],
  brand_color:         ['pro', 'team', 'enterprise'],
  phone_support:       ['enterprise'],
};

export function planHasFeature(plan: Plan, feature: FeatureKey): boolean {
  return FEATURE_PLANS[feature].includes(plan);
}

// The smallest plan that unlocks a given feature — used by the upgrade modal
// to suggest a target. Order matches the price ladder.
const PLAN_ORDER: Plan[] = ['free', 'pro', 'team', 'enterprise'];

export function cheapestPlanFor(feature: FeatureKey): Plan {
  for (const plan of PLAN_ORDER) {
    if (planHasFeature(plan, feature)) return plan;
  }
  return 'enterprise';
}

// Whether a plan represents a billable subscription (vs. free / staff-granted enterprise).
export function isPaidPlan(plan: Plan): boolean {
  return plan !== 'free';
}

// Public copy used by the pricing page and paywall overlays. Kept in sync with
// the Stripe Product metadata generated by scripts/setup-stripe.ts.
export interface PlanCatalogEntry {
  plan: Plan;
  displayName: string;
  monthlyPriceUsd: number | null;   // null = invoice-only (enterprise)
  annualPriceUsd: number | null;
  perSeat: boolean;
  tagline: string;
  features: string[];
}

export const PLAN_CATALOG: PlanCatalogEntry[] = [
  {
    plan: 'free',
    displayName: 'Free',
    monthlyPriceUsd: 0,
    annualPriceUsd: 0,
    perSeat: false,
    tagline: 'Build and self-host GTFS feeds at no cost.',
    features: [
      'Up to 3 saved feeds in the cloud',
      'GTFS ZIP export (host anywhere)',
      'Free forever',
      'Community support',
    ],
  },
  {
    plan: 'pro',
    displayName: 'Pro',
    monthlyPriceUsd: 49,
    annualPriceUsd: 499,
    perSeat: false,
    tagline: 'For individual operators and consultants.',
    features: [
      'Up to 10 saved feeds',
      'Publish 1 feed to a stable URL',
      'Rider-facing embeds + mini-site',
      'Demographic coverage analysis',
      'Cost estimation analysis',
      'Custom brand color',
      'Email support (best-effort)',
    ],
  },
  {
    plan: 'team',
    displayName: 'Team',
    monthlyPriceUsd: 199,
    annualPriceUsd: 1999,
    perSeat: false,
    tagline: 'For transit agencies and consultants serving multiple clients.',
    features: [
      'Unlimited saved feeds',
      'Publish up to 5 feeds',
      'Full analysis: Title VI + propensity heatmap',
      'Unlimited team members in your organization',
      'Cross-org membership (work in unlimited client orgs)',
      'Custom brand color + org logo',
      'Email support (1-2 business day target)',
    ],
  },
  {
    plan: 'enterprise',
    displayName: 'Enterprise',
    monthlyPriceUsd: null,
    annualPriceUsd: null,
    perSeat: false,
    tagline: 'For state DOTs, RTAP networks, and large consortiums.',
    features: [
      'Custom feed and seat limits',
      'Unlimited managed publishing',
      'Branded mini-sites',
      'Full analysis tools',
      'Phone + email support with SLA',
      'Contract terms via PO or invoice',
    ],
  },
];
